# CloudRIG - Gaming apps installation module

Import-Module "$PSScriptRoot\Common"

Function Install-GamingApp {
    [System.Collections.ArrayList]$script:Jobs = @()
    Write-Host "Installing gaming apps..."
    Write-Progress -Activity "Installing gaming apps..." -CurrentOperation "Parsec (1/10)" -PercentComplete 0
    Install-Parsec
    Write-Progress -Activity "Installing gaming apps..." -CurrentOperation "Rainway (2/10)" -PercentComplete 10
    Install-Rainway
    Write-Progress -Activity "Installing gaming apps..." -CurrentOperation "NICE-DCV (3/10)" -PercentComplete 20
    Install-NICEDCV
    Write-Progress -Activity "Installing gaming apps..." -CurrentOperation "Steam (4/10)" -PercentComplete 30
    Install-Steam
    Write-Progress -Activity "Installing gaming apps..." -CurrentOperation "Discord (5/10)" -PercentComplete 40
    Install-Discord
    Write-Progress -Activity "Installing gaming apps..." -CurrentOperation "Origin (6/10)" -PercentComplete 50
    Install-Origin
    Write-Progress -Activity "Installing gaming apps..." -CurrentOperation "Battle.net (7/10)" -PercentComplete 60
    Install-Battlenet
    Write-Progress -Activity "Installing gaming apps..." -CurrentOperation "EpicGames (8/10)" -PercentComplete 70
    Install-EpicGames
    Write-Progress -Activity "Installing gaming apps..." -CurrentOperation "UPlay (9/10)" -PercentComplete 80
    Install-UPlay
    Write-Progress -Activity "Installing gaming apps..." -CurrentOperation "Waiting for end (10/10)" -PercentComplete 90
    Wait-ForJobs
    Write-Progress -Activity "Installing gaming apps..." -CurrentOperation "Done" -PercentComplete 100
}

Function Wait-ForJobs {
    Write-Progress -Activity "Waiting for jobs end..."
    foreach ($Job in $script:Jobs) {
        $Job.WaitForExit(30000)
    }
}

Function Install-Parsec
{
    Write-Host "  * Parsec" -NoNewline
    (New-Object System.Net.WebClient).DownloadFile("https://builds.parsecgaming.com/package/parsec-windows.exe", "$global:CloudRIGInstallBaseDir\Apps\parsec-windows.exe")
    Start-Process -FilePath "$global:CloudRIGInstallBaseDir\Apps\parsec-windows.exe" -ArgumentList '/S' -wait
    Write-host "` - Success!"
}

Function Install-Rainway {
    Write-Host "  * Rainway" -NoNewline
    (New-Object System.Net.WebClient).DownloadFile("https://releases.rainway.com/bootstrapper.exe", "$global:CloudRIGInstallBaseDir\Apps\rainway-bootstrapper.exe")
    Start-Process -FilePath "$global:CloudRIGInstallBaseDir\Apps\rainway-bootstrapper.exe" -ArgumentList '/S' -wait
    Write-host "`  - Success!"
}

Function Install-NICEDCV {
    Write-Host "`  * NICE DCV" -NoNewline
    (New-Object System.Net.WebClient).DownloadFile("https://d1uj6qtbmh3dt5.cloudfront.net/2021.2/Servers/nice-dcv-server-x64-Release-2021.2-11190.msi", "$global:CloudRIGInstallBaseDir\Apps\nice-dcv-server-x64-Release.msi")
    Start-Process -FilePath "$global:CloudRIGInstallBaseDir\Apps\nice-dcv-server-x64-Release.msi" -ArgumentList 'ADDLOCAL=ALL', '/quiet','/norestart','/l*v', 'dcv_install_msi.log' -wait
    Write-host "`  - Success!"

    # Install a wildcard self-signed certificate for all EC2 instances
    # The default certificate generated by the installer does not allow the "Process anyway" option when using Google Chrome, so we generate
    # a CloudRIG custom one.
    Write-Host "`  * NICE DCV - Self-Signed certificate" -NoNewLine
    Start-Process -FilePath "C:\Program Files\OpenSSL-Win64\bin\openssl.exe" -ArgumentList 'req -x509 -new -newkey rsa:4096 -nodes -subj "/C=FR/O=CloudRIG/OU=IT/CN=support@cloudrig.io" -addext "extendedKeyUsage = serverAuth" -keyout C:\Windows\System32\config\systemprofile\AppData\Local\NICE\dcv\dcv.key -out C:\Windows\System32\config\systemprofile\AppData\Local\NICE\dcv\dcv.pem' -Wait | Out-Null
    Restart-Service "DCV Server"  | Out-Null
    Write-host "`  - Success!"

    # Tune DCV to make it better for gaming
    # Based on work of ni-sp https://www.ni-sp.com/support/nice-dcv-tips-and-tricks/#h-adapt-the-dcv-image-quality-for-best-user-experience
    Write-Host "`  * NICE DCV - Configure sessions" -NoNewLine
    $SessionManagementKey = "Registry::HKEY_USERS\S-1-5-18\Software\GSettings\com\nicesoftware\dcv\session-management"
    Set-ItemProperty -Path $SessionManagementKey -Name 'create-session' -Value 1 | Out-Null

    $AutomaticConsoleSessionKey = "Registry::HKEY_USERS\S-1-5-18\Software\GSettings\com\nicesoftware\dcv\session-management\automatic-console-session"
    Set-ItemProperty -Path $AutomaticConsoleSessionKey -Name 'owner' -Value 'Administrator' | Out-Null

    # Enable high performances protocol (QUIC)
    Write-Host "`  * NICE DCV - Enabling QUIC protocol" -NoNewLine
    $ConnectivityManagementKey = "Registry::HKEY_USERS\S-1-5-18\Software\GSettings\com\nicesoftware\dcv\connectivity"
    New-ItemProperty -Path $ConnectivityManagementKey -Name 'enable-quic-frontend' -Value 1 -PropertyType DWord | Out-Null

    Write-Host "`  * NICE DCV - Configuring bandwith (max 50MB, 60fps)" -NoNewLine
    $DisplayManagementKey = "Registry::HKEY_USERS\S-1-5-18\Software\GSettings\com\nicesoftware\dcv\display"
    # Limit to 60 FPS
    New-ItemProperty -Path $DisplayManagementKey -Name 'target-fps' -Value 60 -PropertyType DWord | Out-Null
    # Max allowed bandwidth
    New-ItemProperty -Path $DisplayManagementKey -Name 'qu-bandwidth' -Value 50 -PropertyType Dword | Out-Null
    # Quality window (allows 30% of reduction for limited bandwidth)
    New-ItemProperty -Path $DisplayManagementKey -Name 'quality' -Value '(70, 100)' -PropertyType String | Out-Null
    # Frame tuning
    New-ItemProperty -Path $DisplayManagementKey -Name 'frame-queue-weights' -Value '(8,5,1)' -PropertyType String | Out-Null
    New-ItemProperty -Path $DisplayManagementKey -Name 'frames-in-transit' -Value '(2,8)' -PropertyType String | Out-Null
    # Disable heatmap evaluation
    New-ItemProperty -Path $DisplayManagementKey -Name 'enable-heatmap' -Value 0 -PropertyType Dword | Out-Null
    # Disable the pixel-perfect quality update
    New-ItemProperty -Path $DisplayManagementKey -Name 'enable-qu' -Value 0 -PropertyType Dword | Out-Null
    # Disable dirty screen regions
    New-ItemProperty -Path $DisplayManagementKey -Name 'use-grabber-dirty-region' -Value 0 -PropertyType Dword | Out-Null
}

Function Install-Steam
{
    Write-Host "  * Steam" -NoNewline
    (New-Object System.Net.WebClient).DownloadFile("https://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe", "$global:CloudRIGInstallBaseDir\Apps\SteamSetup.exe")
    Start-Process "$global:CloudRIGInstallBaseDir\Apps\SteamSetup.exe" -ArgumentList '/S' -Wait
    # Start steam as it needs to download the latest version on first run
    Start-Process 'C:\Program Files (x86)\Steam\Steam.exe'
    Write-host "`  - Success!"
}

Function Install-Discord
{
    Write-Host "  * Discord" -NoNewline
    (New-Object System.Net.WebClient).DownloadFile("https://discordapp.com/api/download?platform=win", "$global:CloudRIGInstallBaseDir\Apps\DiscordSetup.exe")
    Start-Process "$global:CloudRIGInstallBaseDir\Apps\DiscordSetup.exe"
    Write-host "`  - Success!"
}

Function Install-Origin
{
    Write-Host "  * Origin" -NoNewline
    (New-Object System.Net.WebClient).DownloadFile("https://origin-a.akamaihd.net/Origin-Client-Download/origin/live/OriginThinSetup.exe", "$global:CloudRIGInstallBaseDir\Apps\OriginThinSetup.exe")
    Start-Process "$global:CloudRIGInstallBaseDir\Apps\OriginThinSetup.exe" -ArgumentList '/SILENT'
    Write-host "`  - Success!"
}

Function Install-EpicGames
{
    Write-Host "  * Epic Games launcher" -NoNewline
    (New-Object System.Net.WebClient).DownloadFile("https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncherInstaller.msi", "$global:CloudRIGInstallBaseDir\Apps\EpicGamesLauncherInstaller.msi")
    Start-Process "$global:CloudRIGInstallBaseDir\Apps\EpicGamesLauncherInstaller.msi" -ArgumentList '/qn /norestart'
    Write-host "`  - Success!"
}

Function Install-UPlay
{
    Write-Host "  * uPlay" -NoNewline
    (New-Object System.Net.WebClient).DownloadFile("https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UplayInstaller.exe", "$global:CloudRIGInstallBaseDir\Apps\UplayInstaller.exe")
    Start-Process "$global:CloudRIGInstallBaseDir\Apps\UplayInstaller.exe" -ArgumentList '/S'
    Write-host "`  - Success!"
}

Function Install-Battlenet {
    Write-Host "  * Battle.net" -NoNewline
    (New-Object System.Net.WebClient).DownloadFile("https://www.battle.net/download/getInstallerForGame?os=win&locale=enUS&version=LIVE&gameProgram=BATTLENET_APP", "$global:CloudRIGInstallBaseDir\Apps\Battle.net-Setup.exe")
    # Exploit a bug of the battle.net installer to make it silent
    Start-Process "$global:CloudRIGInstallBaseDir\Apps\Battle.net-Setup.exe" -ArgumentList '--lang=english'
    Sleep 3
    sleep 25
    Stop-Process -Name "Battle.net-Setup" -ErrorAction 'silentlycontinue'
    Start-Process "$global:CloudRIGInstallBaseDir\Apps\Battle.net-Setup.exe" -ArgumentList '--lang=english','--bnetdir="c:\Program Files (x86)\Battle.net"'
    Write-host "`  - Success!"
}
