name: Scheduled AMI building

# Run it every 3 months
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 1/3 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instancetype: ["g2.2xlarge"]
    steps:
      - uses: actions/checkout@v2
      - name: Execute the automation
        run: |
          aws ssm start-automation-execution --document-name \
            $(aws cloudformation describe-stack-resource --stack-name cloudrig-amifactory-pipeline --logical-resource-id  BuildAMISSMAutomation | jq -r '.StackResourceDetail.PhysicalResourceId') \
            --parameters InstanceType=${{ matrix.instancetype }},Version=$(cat './VERSION')
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1